### ISSUE TITLE
Why Cropped output images

### ISSUE THREAD

**Issue by khaulahzia** [phillipi/pix2pix#109]
I am working on your pix2pix mode. I have been able to train and test the models. i have also tested your pre-trained models. One issue that i am noticing is that the images the model takes as an input and creates a corresponding output is cropped version of the images i provided as input for testing.

For Example for edges2handbags model, i input following image for testing:

![hand-bag-outline_318-73799](https://user-images.githubusercontent.com/30296529/31306239-41b567b8-ab3b-11e7-9c1b-674f691adde5.jpg)

In the results folder, input images is this:

![hand-bag-outline_318-73799](https://user-images.githubusercontent.com/30296529/31306214-cc767910-ab3a-11e7-9fdf-dafc8753afa9.jpg)

and the resulting output is this:

![hand-bag-outline_318-73799](https://user-images.githubusercontent.com/30296529/31306215-db75dac8-ab3a-11e7-914b-e7e7029d028c.jpg)

I am unable to figure out, why are the images exactly halved vertically??

**Comment by khaulahzia** [comment]
I trained another model myself which has also exactly the same issue.
Input i gave:

![0101](https://user-images.githubusercontent.com/30296529/31306261-bdba367c-ab3b-11e7-8ea4-121447601c98.jpg)

Input in the results folder:

![0101](https://user-images.githubusercontent.com/30296529/31306264-d58360a8-ab3b-11e7-8594-26e5ea46c926.jpg)

output:

![0101](https://user-images.githubusercontent.com/30296529/31306266-e1c7a572-ab3b-11e7-8c6c-e81f9016522a.jpg)

Although i didn't get results as i wanted but why the images are cropped first of all?

**Comment by phillipi** [comment]
This is because the code expects the input to be image pairs {A,B} with the A image and B images concatenated side by side to make a big image AB. What's happening is the code expects that you gave it a big AB image, then cuts it in half to get A, which in your case is the left half of the input image.

You will have to modify the code to avoid this, or simply feed in inputs in the required AB format. See [here](https://github.com/phillipi/pix2pix#setup-training-and-test-data) for more details.
