### ISSUE TITLE
ImageGAN question

### ISSUE THREAD

**Issue by bowenc0221** [phillipi/pix2pix#110]
Hi,

You did a fantastic work. I'm trying to reproduce your work in MXNet and I have a question about the implementation of ImageGAN (the 256x256 discriminator). In my understanding, given an input pair of spatial size 256x256 to this discriminator, it should generate a single label for this pair. That is, the spatial size should be reduced to 1x1.

In function defineD_n_layers (https://github.com/phillipi/pix2pix/blob/master/models.lua#L180), ImageGAN is implemented by setting n_layers = 6. However, there are together 6 convolutions with stride = 2, so the size of the image is reduced to 256/(2^6) = 4. The following two convolutions have stride=1, pad=1, so that the final output has a spatial size of 2x2.

My question is, should the second to the last convolution layer has stride=2 so that the output has a spatial size of 1x1?

**Comment by phillipi** [comment]
In the paper, we were using "PatchGAN" and "ImageGAN" to refer to the receptive field sizes of the networks -- the ImageGAN has receptive fields at the output layer that view every input pixel. This doesn't necessarily mean the output has to go to spatial size 1x1. Of course, previous discriminators, like in DCGAN, did usually go to 1x1, so perhaps the terminology is a bit misleading.

For exactly replicating our code, I would stick with the 2x2 architecture. If you do switch to 1x1, be careful with the batchnorm layers, since batchnorm on a 1x1 layer, with batchsize=1, may zero the activations.

Looking forward to seeing the MXNet implementation!

**Comment by mrgloom** [comment]
@phillipi Can you elaborate on
 >be careful with the batchnorm layers, since batchnorm on a 1x1 layer, with batchsize=1, may zero the activations.

 Is it because mean value of 1x1 layer is the same as it's value itself?

**Comment by mrgloom** [comment]
Seems related https://github.com/phillipi/pix2pix/commit/b479b6b7d37f9d7e87dce7f5e627dc3bb7b4a117#commitcomment-21887022
