### ISSUE TITLE
Why different D layers have different strides ? 

### ISSUE THREAD

**Issue by qixiang109** [phillipi/pix2pix#117]
In the function defineD_n_layers(), I notice that for D1, D2, ... they all have strides=2, but for D_{-2} and D_{-1}, they have strides=1. But WHY?

**Comment by phillipi** [comment]
Most layers have stride 2 to achieve downsampling, which increasing the receptive field size of D. The last two layers are stride 1 mainly because we wanted D to have some sufficient depth (capacity) even when the receptive fields are very small, e.g. for the "PixelGAN", which has no downsampling layers. The exact choice of 2 stride=1 layers was somewhat arbitrary -- it seemed to work alright so we stuck with that.
