### ISSUE TITLE
HED postProcess.m Error

### ISSUE THREAD

**Issue by groot-1313** [phillipi/pix2pix#118]
Upon running the postProcess.m file that batch processes multiple mat files to obtain HED edges, I am getting the following error:
    `Not enough input arguments.`
    `line: E = 1-predict`
Any ideas where I can find the function? I have followed all installation instructions as mentioned in the script.

**Comment by phillipi** [comment]
Here's the line: https://github.com/phillipi/pix2pix/blob/ab6d3a6b790ee9d279870dccb5c8b66b035b72eb/scripts/edges/PostprocessHED.m#L46

Matlab appears to be interpreting predict as a function rather than as a variable. The previous line, `load(filePath);`, should have loaded the variable predict, but probably it did not. You can debug it by checking what is saved at `filePath`.
