### ISSUE TITLE
patchGAN and receptive field size

### ISSUE THREAD

**Issue by khryang** [phillipi/pix2pix#122]
Hi~ I have one question about patch size in patchGAN.
In "https://github.com/phillipi/pix2pix/blob/master/scripts/receptive_field_sizes.m" script,

there are mentions about output size,
% fix the output size to 1 and derive the receptive field in the input

1. I wander the output size means spatial size(width * heighth) or output channel?
  but, If that means spatial size -> the output size of  'n_layers == 3' is not '1'.....

2. in your code, does the 'n' value mean 'number of downsampling', except the first layer(that has stride '2')

3. actually what I want to know... is what should I use which number for the 'n' for my 512*512 images and 256*256 images for 70*70 receptive field size!!

please advanced answer!

**Comment by phillipi** [comment]
1. the script is finding the receptive field size for 1 output neuron, which is why it says "fix the output size to 1"

2. yeah, n is number of additional downsampling layers

3. generally if you double the resolution, I think it's a good idea to add 1 to n. However, if you want 70x70 RFs then n=3 will always achieve this, regardless of the resolution.
