### ISSUE TITLE
Trouble reproducing ground truth results

### ISSUE THREAD

**Issue by erthher** [phillipi/pix2pix#159]
Hi,

I am trying to use the evaluation script to reproduce the ground truth results.
The [label](https://github.com/phillipi/pix2pix/blob/master/scripts/eval_cityscapes/evaluate.py#L43) has a shape of (1024, 2048, 3) but the [segmentation result](https://github.com/phillipi/pix2pix/blob/master/scripts/eval_cityscapes/evaluate.py#L48) has a shape of  (1024, 2048). As a result the [fast_hist](https://github.com/phillipi/pix2pix/blob/master/scripts/eval_cityscapes/evaluate.py#L49) function throws the following error:
`IndexError: index 2097152 is out of bounds for axis 1 with size 2097152`.

If I try to select only one of the label channels or use np.repeat to stack the segmentation result with itself I get very poor results for the ground truth (Mean Pixel accuracy < 0.04).

Is that the intended behavior of the script?

Thanks in advance.

**Comment by junyanz** [comment]
@tinghuiz

**Comment by ZoloLongZhuo** [comment]
I meet the same problem too.  And I am so confused about it.I have got this. But I can't get the right metrics....@junyanz Could I get some suggestions?

**Comment by tinghuiz** [comment]
Hi, please refer to the notes under "Evaluating Labels2Photos on Cityscapes" in the README.

**Comment by erthher** [comment]
@tinghuiz Thank you for your reply. 

I'm afraid these notes aren't related to the problem at hand since the problem isn't in the dimensions of the images but in the number of channels.

Just to be sure I uncommented [line 46](https://github.com/phillipi/pix2pix/blob/master/scripts/eval_cityscapes/evaluate.py#L46) but I still got the same error.

**Comment by erthher** [comment]
If anyone else encountered this problem - this is due to evaluating the test set and not the train or validation set. In the Cityscapes dataset the test set doesn't have the same label format and meaning as in the other splits.

**Comment by ZoloLongZhuo** [comment]
@erthher Excuse me . I am so curious about the solution of the problem ? Could I get your email and ask some questions ,plz ?

**Comment by KaitiSt** [comment]
Hello @erthher ,
Did you manage to proceed with the evaluation of the testing set ? If yes, can you please explain how ? 
I am facing the same issue.

**Comment by tinghuiz** [comment]
As mentioned in Section 6.2 "Training details" of the paper, we used the Cityscapes **validation** set for testing.

**Comment by KaitiSt** [comment]
Hello @tinghuiz ,
Thank you for your response. I updated the cityscape directory with the original Cityscape validation set from the Cityscape website , which includes images of size 1024 x 2048 . And, also, I updated the result directory to have my predicted images , which are size 256 x 256 .

I tried different scenarios in order to make the evaluation work . 

Based on the evaluation code the predicted images will be resized from 256 x 256 to the label size which is 1024 x 2048 and push them into the segmentation network. If I keep the code as it is i am getting the below exception : 

**F0415 12:42:11.680351 10204 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory**

Based on your [comment](https://github.com/phillipi/pix2pix/issues/116#issuecomment-350972574) , I can understand that the pre trained model does not work well with 1024 x 2048. So if i remove the resize of the input image to 1024 x 2048 , the segmentation is done , but it's failing in the fast_hist method with the below exception:

**IndexError: index 65553 is out of bounds for axis 0 with size 65536**

But, as per your your [comment](https://github.com/phillipi/pix2pix/issues/116#issuecomment-350972574) once more  , if I resize the original cityscape image - label to 256 x 256 the evaluation is working.

The results though are not so good 

![image](https://user-images.githubusercontent.com/36444767/56125491-b85c7e00-5f81-11e9-96e1-55bf638f6c07.png)

Example:
**0_input (256x256)**
![0_input (256x256)](https://user-images.githubusercontent.com/36444767/56125536-d629e300-5f81-11e9-9c09-49aa5a45a3bb.jpg)

**0_pred (256x256)**
![0_pred (256x256)](https://user-images.githubusercontent.com/36444767/56125586-ee99fd80-5f81-11e9-9449-db60bd389252.jpg)

**0_gt (256x256)**
![0_gt (256x256)](https://user-images.githubusercontent.com/36444767/56125615-feb1dd00-5f81-11e9-97d0-4299a47f74c8.jpg)

**Comment by sigtot** [comment]
@KaitiSt did you ever solve this last problem? We're facing the same issue with the entire image being marked as road (purple).
