### ISSUE TITLE
Reason of using one discriminative network 

### ISSUE THREAD

**Issue by fxia22** [phillipi/pix2pix#18]
Hi, 

Thank you for this cool project. Comparing this work with Pixel level domain transfer(my implementation at https://github.com/fxia22/pldtgan), this work uses only one discriminative network D, instead of a real/fake discriminative network D and an associate/not associate discriminative network. Any reason behind this? Is it because the domain transfer is smaller (input and output well aligned).

Thanks!

**Comment by phillipi** [comment]
Adding an associated/not associated discriminator could be an interesting extension. It seems to have helped not just in pixel level domain transfer, but also in [Reed et al. 2016](https://arxiv.org/pdf/1605.05396v2.pdf).

The reason we didn't pursue that approach is because we were getting good correspondence even without it, and we didn't want to add unnecessary complexity.

Adding the skip connections helps a lot in getting good correspondences. [Reed et al. 2016](https://arxiv.org/pdf/1605.05396v2.pdf) and [Yoo et al. 2016](https://arxiv.org/abs/1603.07442) didn't have these, which may be why they needed a separate network to penalize bad correspondence. Of course, it's probably easier to learn correspondence in our tasks since the input and output are well aligned.

Thanks for the question!
