### ISSUE TITLE
How to turn off the random jitter

### ISSUE THREAD

**Issue by kaihuchen** [phillipi/pix2pix#28]
I am looking for a way to turn off the 'random jitter' mentioned in the paper (which was applied to some experiments there, but not all). Best I can tell, changing the option 'preprocess' should control this, but I got exception if I set it to something other than 'regular' or 'colorization'.

The reason for needing this is that in my experiments with getting cGAN to fill in missing part (e.g., a whole eye) in human faces, I am getting problem with the repaired eye getting out of position or slightly wrong sized , and I would like to turn off this jittering to see if it helps.

Following is an example from my training session, where the right image is the ground truth image, the left image is the input image with the left eye  erased, and at center is the output image with its repaired left eye out of position and slightly too small. 
![20161203114242](https://cloud.githubusercontent.com/assets/13685803/20860742/a3bec318-b94d-11e6-89d7-57ac64ba8882.png).

**Comment by klichukb** [comment]
As far as I researched the code, `data/donkey_folder.lua` has `preprocessAandB` function, which does scaling and random cropping based on random `torch.uniform`.

**Comment by phillipi** [comment]
That's right, you could modify `preprocessAandB`, but a simpler solution is just set `loadSize=256` and `fineSize=256`. This will turn off random jittering since the preprocess function chooses a random crop of size `fineSize` from the loaded image of size `loadSize`. When `fineSize`==`loadSize`, the only possible crop is to take the full image.

Example invocation:
`loadSize=256 fineSize=256 th train.lua`

@kaihuchen, I'm not sure if removing jitter will help for your case. During jitter, the input and output images are translated identically, so I don't think jitter is causing the eye to be misplaced. Doesn't hurt to try though.

**Comment by kaihuchen** [comment]
@phillipi   Your solution is better than other hacks that I can work out. Much appreciated!

Removing the jitter somehow did help as well as I had expected. That is, it worked well for those face samples that have been aligned based on specific criteria, but not for the unaligned ones. 

The majority of the face samples had to be aligned since it seems to be only way to get decent results, and I figure that's because we are so sensitive to even very minor deformities in facial images (unlike other type of images). I suspect that such mostly aligned dataset might have something to do with the problem observed.
