### ISSUE TITLE
Larger image sizes

### ISSUE THREAD

**Issue by julien-arch** [phillipi/pix2pix#45]
It would be great to use pix2pix on larger images, e.g 1024px. I guess one needs to add a couple of layers and change some parameters?

**Comment by phillipi** [comment]
You should be able to run the provided architectures on 1024px, since the net is fully convolutional (note that there may be some boundary issues to resolve if you use a size that is not a power of 2).

However, using the architecture in `defineG_unet` won't actually make use of all the information in a 1024px image -- the receptive fields of each output pixel will only be 256px. To let the net see the complete 1024px image, you could add two more down/up-sampling layers to the front/back of the network.
