### ISSUE TITLE
Output size discriminator

### ISSUE THREAD

**Issue by noob16** [phillipi/pix2pix#49]
Hi,

why are you using an output size of 1x30x30 for the discriminator? and not just 1x1x1?

Thanks!

**Comment by phillipi** [comment]
This is because the (default) discriminator is a "PatchGAN" (Section 2.2.2 in the [paper](https://arxiv.org/pdf/1611.07004v1.pdf)). This discriminator slides across the generated image, convolutionally, trying to classify if each overlapping 70x70 patch is real or fake. This results in a 30x30 grid of classifier outputs, each corresponding to a different patch in the generated image.

**Comment by kenshinzh** [comment]
@phillipi If I want to classify each overlapping a minor patch eg. like 16 x 16 patch is real or fake, should this results in a which size grid of classifier outputs? any formula or hints can provide?

**Comment by phillipi** [comment]
You can use this script to determine the receptive field (e.g., 16 x 16) of a given architecture:
https://github.com/phillipi/pix2pix/blob/master/scripts/receptive_field_sizes.m

I'm not sure what the formula would be for calculating output grid size given desired receptive field. For a given architecture, you can always check the output size by running it on an image and calling `out:size()` on the output `out`.

**Comment by kenshinzh** [comment]
@phillipi Thank you for you quick response. I am not familiar with the Matlab. Would you please be more specify how can I get the output with the script you provided. Thank you so much.

**Comment by phillipi** [comment]
That script gives you the receptive field of a neuron. The equation to compute the input receptive field size from a given output receptive field size is (for a single convolutional layer) is:
input_size = (output_size - 1) * stride + kernel_size

You can call this recursively to compute the receptive field sizes across multiple layers.

**Comment by kenshinzh** [comment]
@phillipi Thank you for you kind explanation. I am sorry that I didn't define my question well. The problem is when I use 70*70 patch GAN as discriminator in code, the output is not as sharp as what described in the paper in some occasion.  
<img width="282" alt="screen shot 2017-06-25 at 1 37 23 pm" src="https://user-images.githubusercontent.com/24644324/27513904-7897bf42-59ab-11e7-9dab-2b65d0f4bcc0.png"> This looks good, but my results is not sharp enough as sample

So I wonder maybe the patch GAN size as default code is 70*70 is too large for the discriminator to classify the fake or real. If I want to enhance the sharpness should I enlarge the patch size or decrease the patch size? or any other suggestions ?

**Comment by junyanz** [comment]
@kenshinzh  what's your input and output? To produce good colorization results, one needs to map `L` to `ab`.  Look at [Notes on Colorization](https://github.com/phillipi/pix2pix#notes-on-colorization) for more details.

**Comment by kenshinzh** [comment]
Actually, my experments is from a B2A direction which is not the color corrections. I just take this B/W for illustration. all the input image is as the demo 256*256

**Comment by phillipi** [comment]
In the colorizations in the paper, we concatenate the predicted `ab` map with the ground truth `L`. This has the effect of making the results look nice and crisp since most of the high frequencies are in the `L` channel. If you just look at the raw predicted `ab` it tends to look less sharp.

I don't think there is a simple relationship between discriminator patch size and and sharpness. In practice 70x70 usually works pretty well for me, but you could try a few variants to see what works in your application.

**Comment by kvmanohar22** [comment]
@phillipi  Just wanted to confirm my understanding of PatchGAN. Please point out if there  is a mistake.

Say the generated image has dimensions of `HxWx3`, we have a `70x70` patchGAN discriminator. In order to determine if the image is real or fake, `70x70` patch from the generated image is taken and passed through a discriminator to produce a single scalar. On extracting each such `70x70` patch convolutionally from the generated image and averaging the obtained scalars for each patch, I get the final probability of whether the image is real or fake ?

**Comment by phillipi** [comment]
Yep that's right!
