### ISSUE TITLE
run generator on 512 by 512

### ISSUE THREAD

**Issue by bluerythem** [phillipi/pix2pix#67]
Hi,

Can you explain the way to train on 256 by 256 by infer on 512 by 512. Are image stitching necessary? Are there more elegant ways?

Thank you!

**Comment by junyanz** [comment]
You can train your model on randomly cropped 256x256 patches. During the inference, the 256x256 model is fully convolutional so that it can run on images with arbitrary sizes. See [fully convolutional networks](https://people.eecs.berkeley.edu/~jonlong/long_shelhamer_fcn.pdf) for more details.

**Comment by bluerythem** [comment]
Thanks, it works well.

**Comment by nonoesp** [comment]
@bluerythem how did you make it work?

**Comment by phillipi** [comment]
It shouldn't require anything special. You can always run the default 256x256 generator on larger images at test time, since it is applied in a fully convolutional fashion. There is one important detail though: without modification, you will only be able to run on images whose size is a power of 2. I would suggest padding your big images to the nearest power of 2 (pad with zeros, since it was trained by default with zero padding).

**Comment by phillipi** [comment]
One other important limitation I should mention: you may run out of memory. For example, the default net, on a 12GB card, will only be able handle at most 512x512 (I think). You could reduce the number of channels if you want to scale bigger.

**Comment by nonoesp** [comment]
Thanks I'll give it a try.
